export const background = '#FFFFFF'

export const black = '#0B1F35'
export const white = '#FFFFFF'
export const grey = '#6D7986'
export const lightGrey = '#B0B6BE'
export const red = '#D64238'
export const yellow = '#facd02'
export const blue = '#2980B9'
export const button = '#facd02'
export const backroundPrimary = '#FFFFFF'
export const backroundSecondary = '#F2F3F3'
export const input = '#F8F8F8;'
export const orange = 'orange'
